### ISSUE TITLE
Select queries are not imploding

### ISSUE THREAD

**Issue by andersonda** [ecu-pase-lab/mysql-query-construction-analysis#1]
Select queries parse but do not implode correctly. For reference, this is what I am using as a guide to build the grammar https://dev.mysql.com/doc/refman/5.7/en/expressions.html

**Comment by andersonda** [comment]
https://dev.mysql.com/doc/refman/5.7/en/select.html is another section of the reference I have been using as a guide that is relevant to this.

**Comment by mahills** [comment]
At this point I've changed the grammar but not the implode. Once the grammar is more stable (or we cut over to using the other parser) we can revisit this.
